### ISSUE TITLE
Uncaught exception using basic example

### ISSUE THREAD

**Issue by spemmons** [brigand/react-zeroclipboard#38]
I'm getting the following error using a simple instance following the example:

 `<ReactZeroClipboard text={ token }><button>COPY</button></ReactZeroClipboard>`

I'm using webpack and React 15.4, but otherwise not sure what information might help.

Any ideas?

`Uncaught Error: Error: An invalid exception was thrown.
    at HTMLObjectElement.swf.(anonymous function) (<anonymous>:19:32)
    at _setHandCursor (http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.js:1678:28)
    at Function._focus (http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.js:707:5)
    at Function.ZeroClipboard.focus.ZeroClipboard.activate (http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.js:1984:19)
    at HTMLButtonElement._elementMouseOver (http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.js:2380:21)`

**Comment by brigand** [comment]
@spemmons you can search "_setHandCursor" and find a bunch of zeroclipboard issues on the subject. Some point to cdnjs being part of the problem. If you include zeroclipboard yourself from a local file it might work, but it needs to be a global variable.

Let me know if that fixes the problem and I'll add a note in the readme.

**Comment by spemmons** [comment]
Thanks. I'm trying to get using the locally-served swf file working and am having some webpack loader issues that I haven't figured out yet. I will post an update later.

**Comment by spemmons** [comment]
I was able to successfully get it working w/ webpack by using with the following:

`<ReactZeroClipboard swfPath={ require('react-zeroclipboard/assets/ZeroClipboard.swf') }>...`

**Comment by brigand** [comment]
Cool! Added a note in the readme.
